### ISSUE TITLE
masymos-docker: suppress docker delete error messages on running the scripts

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-core#22]
- [x] handle and hide all unnecessary outputs; only output INFO and real ERROR

:information_source: @ronhenkel

**Comment by BradleyScrim** [comment]
@ronhenkel , i changed the scripts to only output INFO, and ERROR on error. I tested every step in every condition on Linux.

Please check, if it's still running on windows, branch [windows-compatibility](https://github.com/MaSyMoS/masymos-docker/tree/windows-compatibility)

1. run `cleanup.sh`
1. **please remove all files from the repository fist to get rid of the cloned repos and the generated and copied jar files**
1. revert the repository and pull
1. test `jar-builder/maven-build-masymos-jars.sh`
1. test `server-integration/copy_own_data_into_docker_volume.sh`
1. test `server-integration/run-neo4j-server.sh`

Thanks!

**Comment by ronhenkel** [comment]
runs like a charme :-D

**Comment by BradleyScrim** [comment]
:information_source: added docs to core; merged changes into master
